source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'AIUIKit_Example' do
  pod 'AIUIKit', :path => '../'

  target 'AIUIKit_Tests' do
    inherit! :search_paths
  end
end
